### PR TITLE
add check for user defined hostname

### PR DESCRIPTION
**Pull request by targhs**
#61 

Is it how we are expecting it to be? Can add to documentation if this seems good.
Also any suggestions as to how to write test cases for this. Current tests already fails. Shall we use something like msw to mock requests for testing the custom host functionality?

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Is it how we are expecting it to be?

👍

**Comment by sindresorhus** [comment]
The test need some kind of mocking, yes.

**Comment by targhs** [comment]
Thanks. Will add test cases too.

**Comment by targhs** [comment]
I am not that much comfortable with AVA for testing. It might take some time (or forever) for me to get this done. You could merge this if that's ok. I can add test cases later on as and when i get some spare time.

**Comment by sindresorhus** [comment]
> You could merge this if that's ok.

I'm not interested in merging untested code.

> I can add test cases later on as and when i get some spare time.

From experience, that never happens.

**Comment by sindresorhus** [comment]
Closing this for now.

**Pull request closed without merging**
