### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jfoclpf**
some people not that versed on promises might get initially confused. I think this change clarifies it

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I don't see how this makes it any clearer. It also doesn't change anything regarding the promise.

**Comment by jfoclpf** [comment]
What I mean is that it should be more clear that `online` is a boolean that
says whether there is internet.

I also suggest a sync workaround so that we don't have to insert all our
code into the `then` enclosure

**Comment by SamVerschueren** [comment]
It's already clear from the usage example. First of all by the name of the result, and second of all by the console.log which shows the output of the variable.

> I also suggest a sync workaround

I don't think this is possible. Check the [How it works](https://github.com/sindresorhus/is-online/blob/master/readme.md#how-it-works) section. Network requests are being made. You don't want to run them synchronously. Not even sure if Node.js supports this.

**Comment by jfoclpf** [comment]
But if there is a `.then` I suppose a `Promise` is returned. Can't we make
something like `let online = await isOnline ();` or similar?

Thx

**Comment by SamVerschueren** [comment]
It is a Promise. So yes you can do `await isOnline()`if your environment supports it.

**Comment by jfoclpf** [comment]
Thank you

And the return of `await isOnline()` is also a boolean saying whether there
is Internet or not?

**Comment by SamVerschueren** [comment]
Yes. `async/await` is just syntactical sugar on top of promises. So the result of the promise is the result of the await call.

**Comment by jfoclpf** [comment]
Thank you. Thus, as a mere suggestion, these two lines could be added to `
readme.md` to apply a pseudo-sync approach:

`let online = await isOnline();`
`console.log (online); //true if there is Internet`

**Comment by SamVerschueren** [comment]
The example is clear that it's a Promise. It's not up to every library author to explain how promises work in an async/await environment. So as long as Node 8 (I believe it ships with async/await, or was it Node 9?) is not the standard, we will not change our documentation.

**Pull request closed without merging**
